language: ruby

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without development --jobs=3 --retry=3

sudo: false

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.3
  - 2.5.1
  - jruby-9.1.17.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
